### ISSUE TITLE
(II) Ná prófunarkeyrslu HZ

### ISSUE THREAD

**Issue by G0rocks** [G0rocks/Staerdfraedigreining-IV-lokaverkefni#5]
Setjið λ = 1/100 , L1 = L2 = 1, h = 1/4 og veljið w, v eins og hér
w(x) = 1 , 0 ≤ x ≤ 1 , v(x) = 0 , 0 ≤ x ≤ 1 .

![image](https://user-images.githubusercontent.com/44577486/113005602-2648e280-9164-11eb-9f4e-72a2afc3e719.png)

**Comment by G0rocks** [comment]
Fattaði að við getum ekki lokað þessu því við erum ekki búin að ná prófunarkeyrslunni. Þurfum að vera með Helmholtzeq fall sem virkar almennilega til þess.

Einnig, athugaðu að x í for loop er ekki notað neinsstaðar og er algjörlega gagnslaust í þeirri lykkju.

Þurfum einnig að nota `disp("Stuff to display here")` til að sýna í keyrslu hvort að við séum með rétt HZ fylki. Sé fyrir mér að við þurfum að setja þetta fylki, sem er gefið upp að sé rétt lausn, getum kallað það HZ_lausn eða eitthvað og skrifum `HZ_lausn-HZ` til að bera það saman og athugum hvort að öll gildin séu minni en machine epsilon til að vera viss um að þetta sé rétt hjá okkur.

**Comment by doramagnea** [comment]
Já það meikar sens. 
Hvernig ætti ég þá frekar að skilgreina x á bili 0 til 1? 

Ég skal bæta inn réttu HZ fylki í þetta líka.

**Comment by G0rocks** [comment]
Til að skilgreina x á bili `[a,b]` þá gerir maður
`x = a:b` eða `x = a:c:b` til að það sé skilgreint með skrefastærðina `c`
Þá færðu samt vigur `x` með `x(1)=a` og `x(n)=b` þ.s. `n` er fjöldi skrefa.

Annars óháð því hvernig maður myndi skilgreina x sem þetta bil þá er ég ekki viss um hvort við þurfum þess. Kíktu á hliðarskilyrðin í verkefninu, þegar `x` er á þessu bili sem við erum með `[0,L_1]` þá er `u(x,0) = w(x)` og `u(x,L_2)=v(x)` sem er skilgreint sem 1 og 0 í prófunarkeyrslunni. Skulum útbúa föll v_HZ.m og w_HZ.m fyrir þau held ég, bý til issue.

Ég er ekki 100% viss. Hér uppi er allavega leið til að skrilgreina `x` en ef þú vilt gera það með for lykkju þá virkar þessi sem þú ert með núna ekki, gætir gert eitthvað eins og
```
n = 100;
h_x = L1./n;
for i = 1:n
    x(i) = i.*h_x;
end
```
Því
```
for x = 0:1
    w = 1;
    v = 0;
end
```

Skilgreinir `x` sem double 1x1 vigur. Þegar for lykkjunni er lokið þá er `x=1` afþví 1 er lokagildið sem `x` tekur í þessari for lykkju.

**Comment by G0rocks** [comment]
Fixed in a commit close to this one: d092c67410db828257576612b19ed11564931ccc (if not that one)
